name:                hscc
version:             0.1.0.0
github:              "Vigilans/hscc"
license:             MIT
author:              "Vigilans"
maintainer:          "vigilans@foxmail.com"
copyright:           "2019 Vigilans"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Vigilans/hscc#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- mtl
- hspec
- parsec
- multimap
- array
- set-monad

default-extensions:
- ViewPatterns
- MonadComprehensions
- FlexibleContexts
- NamedFieldPuns

library:
  source-dirs: src

executables:
  hscc-lex:
    main:                Main.hs
    source-dirs:         app/lex
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hscc

  hscc-yacc:
    main:                Main.hs
    source-dirs:         app/yacc
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hscc

tests:
  hscc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hscc
    - hspec
    - QuickCheck
